### ISSUE TITLE
kafka broker seems unresponsive for grafzahl and jgrafzahl

### ISSUE THREAD

**Issue by elmiko** [radanalyticsio/radanalyticsio.github.io#168]
when running these tutorials i am seeing an error come from the word-fountain pod. it would appear that there is an issue with the kafka broker:

```
$ oc logs -f dc/word-fountain                                                                                                                         
---> Running application from Python script (app.py) ...                                                                                              
Traceback (most recent call last):                                                                                                                    
  File "app.py", line 31, in <module>                                                                                                                 
servers=['apache-kafka:9092'], topic=word-fountain, rate=3, count=-1                                                                                  
    producer.send(topic, random.choice(words))                                                                                                        
  File "/opt/app-root/src/.local/lib/python2.7/site-packages/kafka/producer/kafka.py", line 504, in send                                              
    self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)                                                                               
  File "/opt/app-root/src/.local/lib/python2.7/site-packages/kafka/producer/kafka.py", line 631, in _wait_on_metadata                                 
    "Failed to update metadata after %.1f secs." % max_wait)                                                                                          
kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.                     
```

**Comment by elmiko** [comment]
@mattf any thoughts?

**Comment by elmiko** [comment]
the kafka sources have changed for the grafzahl applications, closing this issue
